name: 'Cloud Express workflow'
description: ''
author: 'kvendingoldo'

branding:
  icon: 'play-circle'
  color: 'green'

inputs:
  base_url:
    description: ''
    required: false
    default: 'https://api.cloudexpress.app'
  timeout:
    description: ''
    required: false
    default: '900'
  interval:
    description: ''
    required: false
    default: '2'
  project_id:
    description: ''
    required: true
    default: ''
  component_id:
    description: ''
    required: true
    default: ''
  new_image:
    description: ''
    required: true
    default: ''
  debug:
    description: ''
    required: false
    default: 'false'
  docker_registry_url:
    description: ''
    required: false
    default: ''
  docker_registry_username:
    description: ''
    required: false
    default: ''
  docker_registry_password:
    description: ''
    required: false
    default: ''

outputs:
  status:
    description: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
